In [5]:
#Cargando el dataset de las canciones de spotify:

import pandas as pd 

df = pd.read_csv("universal_top_spotify_songs.csv")
df.head()

,spotify_id,name,artists,daily_rank,daily_movement,weekly_movement,country,snapshot_date,popularity,is_explicit,...,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
0,2RkZ5LkEzeHGRsmDqKwmaJ,Ordinary,Alex Warren,1,1,0,NaN,2025-06-11,95,False,...,2,-6.141,1,0.0600,0.704000,0.000007,0.0550,0.391,168.115,3
1,42UBPzRMh5yyz0EDPr6fr1,Manchild,Sabrina Carpenter,2,-1,48,NaN,2025-06-11,89,True,...,7,-5.087,1,0.0572,0.122000,0.000000,0.3170,0.811,123.010,4
2,0FTmksd2dxiE5e3rWyJXs6,back to friends,sombr,3,0,1,NaN,2025-06-11,98,False,...,1,-2.291,1,0.0301,0.000094,0.000088,0.0929,0.235,92.855,4
3,7so0lgd0zP2Sbgs2d7a1SZ,Die With A Smile,"Lady Gaga, Bruno Mars",4,0,-1,NaN,2025-06-11,91,False,...,6,-7.727,0,0.0317,0.289000,0.000000,0.1260,0.498,157.964,3
4,6dOtVTDdiauQNBQEDOtlAB,BIRDS OF A FEATHER,Billie Eilish,5,1,0,NaN,2025-06-11,100,False,...,2,-10.171,1,0.0358,0.200000,0.060800,0.1170,0.438,104.978,4

In [6]:
# Keep only the columns Moodify needs
df = df[
    [
        "spotify_id",
        "name",
        "artists",
        "album_name",
        "popularity",
        "danceability",
        "energy",
        "valence",
        "tempo"
    ]
].copy()

# Remove songs with missing values
df = df.dropna(
    subset=[
        "spotify_id",
        "name",
        "artists",
        "energy",
        "valence"
    ]
)

# Remove duplicate songs
df = df.drop_duplicates(
    subset="spotify_id"
).reset_index(drop=True)

print("Songs available:", len(df))

df.head()

Songs available: 2084

,spotify_id,name,artists,album_name,popularity,danceability,energy,valence,tempo
0,2RkZ5LkEzeHGRsmDqKwmaJ,Ordinary,Alex Warren,"You'll Be Alright, Kid (Chapter 1)",95,0.368,0.694,0.391,168.115
1,42UBPzRMh5yyz0EDPr6fr1,Manchild,Sabrina Carpenter,Manchild,89,0.731,0.685,0.811,123.010
2,0FTmksd2dxiE5e3rWyJXs6,back to friends,sombr,back to friends,98,0.436,0.723,0.235,92.855
3,7so0lgd0zP2Sbgs2d7a1SZ,Die With A Smile,"Lady Gaga, Bruno Mars",MAYHEM,91,0.519,0.601,0.498,157.964
4,6dOtVTDdiauQNBQEDOtlAB,BIRDS OF A FEATHER,Billie Eilish,HIT ME HARD AND SOFT,100,0.747,0.507,0.438,104.978

In [7]:
#classifying song: 
def classify_song(row):
    valence = row["valence"]
    energy = row["energy"]
    
    #positive + energetic
    
    if valence >= 0.6 and energy >= 0.6:
        return "happy"
    
    #positive and lower energy
    
    if valence >= 0.6 and energy < 0.6:
        return "calm"
    
    #negative
    
    if valence < 0.4 and energy < 0.6:
        return "sad"
    
    #in the middle
    
    else: 
        return "neautral"
    
df["mood"] = df.apply(
    classify_song, axis=1
)

In [8]:
#testing

df["mood"].value_counts()

mood
neautral    908
happy       680
sad         325
calm        171
Name: count, dtype: int64

In [9]:
from transformers import pipeline

sentiment_pipeline = pipeline(
    task="sentiment-analysis",
    model="distilbert-base-uncased-finetuned-sst-2-english"
)

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

In [10]:
#logic for recommending

def recommend_song(user_text):
    result = sentiment_pipeline(user_text)
    
    sentiment = result[0]["label"]
    confidence = result[0]["score"]
    
    if sentiment == "POSITIVE":
        
        if confidence >= 0.85:
            target_mood= "happy"
        else:
            target_mood="calm"
            
    else:
        
        if confidence >= 0.85:
            target_mood = "sad"
        else: 
            target_mood = "intense"
            
    songs = df[df["mood"]==target_mood]
    
    #Prefer recognizable song:
    
    popular_song= songs[songs["popularity"]>=60]
    
     # Fallback in case there aren't enough
    if len(popular_song) >= 5:
        songs = popular_song

    recommendations = songs.sample(
        min(5, len(songs))
    )

    return {
        "sentiment": sentiment,
        "confidence": round(confidence, 3),
        "mood": target_mood,
        "songs": recommendations[
            [
                "name",
                "artists",
                "album_name",
                "popularity",
                "valence",
                "energy",
                "spotify_id"
            ]
        ]
    }

In [ ]:
#testing

#result = recommend_song(
    #"I feel lonely and I had a terrible day."
#)

#print("Sentiment:", result["sentiment"])
#print("Confidence:", result["confidence"])
#print("Mood:", result["mood"])

#result["songs"]

Sentiment: NEGATIVE
Confidence: 0.998
Mood: sad

,name,artists,album_name,popularity,valence,energy,spotify_id
154,111,Yan Block,111,86,0.140,0.498,2SPBFiD8iITb8CKJGz1TEQ
1742,Pa Tripea,"Lil Naay, Huan62",Pa Tripea,67,0.393,0.536,2NKe3jG4Tsdarixp87OnCE
1102,Vasarą galvoj minoras,Katarsis,Vasarą galvoj minoras,61,0.282,0.276,1wGPGvj0moDoKMMVwFWFLj
1430,Selamat (Selamat Tinggal),"Virgoun, Audy",Selamat (Selamat Tinggal),81,0.372,0.581,1mruWrUwAVe2XkksUQiaHK
135,Hà Nội,"Obito, Shiki, VSTRA",Đánh Đổi,68,0.365,0.368,5PGh9MyKry8slG5AfvD1eD